# Generated by Django 5.0.6 on 2024-07-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deletesub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='hari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(max_length=200)),
                ('Register_No', models.CharField(max_length=20)),
                ('Student_Semister', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('password', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Staff_Name', models.CharField(max_length=250)),
                ('Password', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StaffDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Subject', models.CharField(choices=[('PYTHON', 'Python'), ('SQL', 'SQL'), ('FRONTEND', 'Frontend'), ('DJANGO', 'Django')], max_length=20)),
                ('Experience', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Reg_No', models.CharField(max_length=20)),
                ('Sem', models.IntegerField()),
                ('Sql', models.IntegerField(default=None)),
                ('Frontend', models.IntegerField(default=None)),
                ('python', models.IntegerField(default=None)),
                ('Django', models.IntegerField(default=None)),
                ('Maximum_Marks', models.IntegerField(default=100)),
                ('Obtained_Marks', models.IntegerField(default=None)),
                ('Total_Marks', models.IntegerField(default=None)),
                ('Percentage', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject_Name', models.CharField(max_length=100)),
            ],
        ),
    ]
